export const GET_LIST_FOOD = "GET_LIST_FOOD";
export const SET_PACKAGE_ITEM = "SET_PACKAGE_ITEM";
export const GET_FOOD = "GET_FOOD";
export const GET_LIST_FOODCATEGORY = "GET_LIST_FOODCATEGORY";
export const GET_SHIPPER_ACTIVE_ACCOUNT = "GET_SHIPPER_ACTIVE_ACCOUNT";
export const GET_COUNT = "GET_COUNT";
export const GET_LIST_PREPARE_ORDER_BY_WEEK = "GET_LIST_PREPARE_ORDER_BY_WEEK";
export const GET_LIST_STATIONS = "GET_LIST_STATIONS";
export const SET_VALUE_TAG = "SET_VALUE_TAG";
export const GET_LIST_USER = "GET_LIST_USER";
export const GET_LIST_KITCHEN = "GET_LIST_KITCHEN";
export const GET_LIST_REQ = "GET_LIST_REQ";
export const KITCHEN_GET_PROFILE = "KITCHEN_GET_PROFILE";
export const GET_LIST_STATION_OF_KITCHEN = "GET_LIST_STATION_OF_KITCHEN";
export const GET_LIST_ORDER_TO_CREATE = "GET_LIST_ORDER_TO_CREATE";
export const GET_LIST_SLOT = "GET_LIST_SLOT";
export const GET_TRIP_BY_STATUS = "GET_TRIP_BY_STATUS";
export const GET_LIST_FEEDBACK = "GET_LIST_FEEDBACK";
export const GET_LIST_SUB = "GET_LIST_SUB";
export const FILLTER_RATE = "FILLTER_RATE";
export const SET_DATE_RANGE = "SET_DATE_RANGE";
export const KITCHEN_GET_LIST_ORDER = "KITCHEN_GET_LIST_ORDER";
export const ADMIN_GET_LIST_ORDER = "ADMIN_GET_LIST_ORDER";

export const GET_LIST_PACKAGE_FOOD = "GET_LIST_PACKAGE_FOOD";
export const GET_LIST_GROUP_FOOD = "GET_LIST_GROUP_FOOD";
export const GET_LIST_TIME_FRAME = "GET_LIST_TIME_FRAME";
export const GET_PACKAGE_FOOD = "GET_PACKAGE_FOOD";
export const GET_LIST_SHIPPER = "GET_LIST_SHIPPER";
export const CREATE_SHIPPER = "CREATE_SHIPPER";
export const GET_LIST_FOOD_BY_FOODGROUP_ID = "GET_LIST_FOOD_BY_FOODGROUP_ID";
export const GET_LIST_STATIONS_KITCHENID = "GET_LIST_STATIONS_KITCHENID";
export const REFRESH_TOKEN = "REFRESH_TOKEN";

export const GET_LIST_TIME_FRAME_BY_ID = "GET_LIST_TIME_FRAME_BY_ID";

export const GET_LIST_FOOD_ACTIVE = "GET_LIST_FOOD_ACTIVE";
export const GET_PROFILE = "GET_PROFILE";
export const GET_SHIPPER_ACTIVE = "GET_SHIPPER_ACTIVE";
export const GET_LIST_SHIPPER_BY_IDKITCHEN = "GET_LIST_SHIPPER_BY_IDKITCHEN";
/// gởi đi message
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const LOGIN_USER = "LOGIN_USER";
export const GET_LIST_CATE_PACKAGE = "GET_LIST_CATE_PACKAGE";
export const GET_LIST_FREE_SHIPPER = "GET_LIST_FREE_SHIPPER";

export const GET_ACCOUNT_CUSTOMER = "GET_ACCOUNT_CUSTOMER";
export const GET_ACCOUNT_ADMIN = "GET_ACCOUNT_ADMIN";
export const GET_ACCOUNT_MANAGER = "GET_ACCOUNT_MANAGER";
export const GET_ACCOUNT_SHIPPER = "GET_ACCOUNT_SHIPPER";
export const GET_ACCOUNT_KITCHEN = "GET_ACCOUNT_KITCHEN";

export const GET_LIST_SHIPPER_OF_KITCHEN = "GET_LIST_SHIPPER_OF_KITCHEN";
export const GET_SHIPPER_BY_ID = "GET_SHIPPER_BY_ID";
export const GET_LIST_ORDER_BY_DATE = "GET_LIST_ORDER_BY_DATE";
export const GET_LIST_GROUPFOOD_BY_STATUS = "GET_LIST_GROUPFOOD_BY_STATUS";

export const GET_LIST_PREPARE_ORDER_BY_DATE = "GET_LIST_PREPARE_ORDER_BY_DATE";

export const GET_LIST_DELIVERY = "GET_LIST_DELIVERY";

export const GET_SHIPPER_STATUS = "GET_SHIPPER_STATUS";

export const GET_LIST_KITCHENID = "GET_LIST_KITCHENID";

export const GET_LIST_KITCHEN_ACTIVE = "GET_LIST_KITCHEN_ACTIVE";
// session
export const GET_LIST_SESSION = "GET_LIST_SESSION";
export const FILLTER_FLAG = "FILLTER_FLAG";
export const GET_LIST_TRIP = "GET_LIST_TRIP";
export const GET_LIST_TRIP_BY_ID = "GET_LIST_TRIP_BY_ID";
export const GET_LIST_SESSION_DETAIL = "GET_LIST_SESSION_DETAIL";
export const GET_LIST_TOTALFOOD = "GET_LIST_TOTALFOOD";
